name: Pre-build NuxtJS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Set current date as ENV / CURRENT_TIME
        run: echo "::set-env name=CURRENT_TIME::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run Python Script
        run: python .
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
